name: 🙏 Welcome First Time Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      if: ${{ github.event.sender.login != github.repository_owner }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          # Congratulations 🚀
          
          You have created your first Issue on Nike. 
        
        pr-message: |
          # Congratulations 🎊
          
          Your have made your first contribution in Nike. Make sure to star this repo 💚
